### ISSUE TITLE
Any plans to publish this on pub.dartlang.org?

### ISSUE THREAD

**Issue by scriptsrc** [jgrowl/satellizer.dart#1]
```
/usr/local/opt/dart/libexec/bin/pub get
Resolving dependencies...
Could not find package satellizer at https://pub.dartlang.org.
```

https://pub.dartlang.org/search?q=satellizer

**Comment by jgrowl** [comment]
I haven't touched this project in quite a while. I apologize but I probably won't make any additional contributions. It was mostly copypasta from the satellizer js project and it was only the most basic functionality it if I remember. Feel free to fork and take over if you want. RIP.
